#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


secondary_output=$(xrandr | grep "HDMI-1-1" | cut -f2 -d " ")
 
if [[ "$secondary_output" == "connected" ]]; then
	xrandr --output eDP-1 --off
	xrandr --output HDMI-1-1 --mode 1920x1080 --primary --rate 144
fi


# Get mouse ID
mouse_id=$(xinput | grep -w "Logitech USB Receiver" | head -n 1 | grep -o 'id=[0-9][0-9]' | sed 's/id=//')

# Set mouse sensitivity
xinput --set-prop $mouse_id 'Coordinate Transformation Matrix' 0.55 0 0 0 0.55 0 0 0 1

xsetroot -cursor_name left_ptr
nitrogen --set-zoom-fill --save $HOME/Documents/Wallpapers/nord-street.png
nitrogen --restore &
picom -f &
exec bspwm
